title: "Nombre Apellido | Perfil profesional y academico"
email: "tu.correo@example.com"
description: >-
  Web personal para presentar perfil profesional, formacion, proyectos
  y publicaciones.
baseurl: "/website"
url: "esettes.github.io"
lang: es
timezone: Europe/Madrid
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: "<!--more-->"
plugins:
  - jekyll-feed
collections:
  projects:
    output: true
    permalink: /projects/:name/
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
